import { Activity, AlertTriangle, BookOpen, CalendarClock, ClipboardCheck, Database, FileBarChart2, FileSearch, FileText, Footprints, Home, Radar, RefreshCw, Send, UserCheck } from 'lucide-react'

import type { IcmRouteMeta, ModuleCategory } from './types'

export const categoryNames: Record<ModuleCategory, string> = {
  plan: '计划',
  data: '数据',
  review: '审查',
  workpaper: '审查记录',
  rectify: '整改',
}

export const icmRoutes: IcmRouteMeta[] = [
  {
    path: '/workplace',
    title: '首页',
    pageId: 'stage_workplace',
    category: 'plan',
    categoryName: categoryNames.plan,
    description: '待办、执行情况、问题排行和整改进度的日常入口。',
    icon: Home,
    layout: '待办事项 → 执行概览 → 快捷入口',
  },
  {
    path: '/plan-workbench',
    title: '计划与派发',
    pageId: 'stage_plan_dispatch',
    category: 'plan',
    categoryName: categoryNames.plan,
    description: '专项计划、任务分解、人员分配和资料清单。',
    icon: ClipboardCheck,
    layout: '计划列表 → 计划详情 → 任务与资料清单',
  },
  {
    path: '/task-center',
    title: '任务中心',
    pageId: 'stage_task_center',
    category: 'plan',
    categoryName: categoryNames.plan,
    description: '检查任务树、甘特排程、进度跟踪与审批节点。',
    icon: CalendarClock,
    layout: '计划/任务树 → 甘特/列表视图 → 任务详情',
  },
  {
    path: '/dispatch-center',
    title: '派发中心',
    pageId: 'stage_dispatch_center',
    category: 'plan',
    categoryName: categoryNames.plan,
    description: '任务派发、资源协调、进场通知与资料需求闭环。',
    icon: Send,
    layout: '任务拆分 → 资源协调 → 进场管理',
  },
  {
    path: '/data-collect',
    title: '数据采集',
    pageId: 'stage_data_collect',
    category: 'data',
    categoryName: categoryNames.data,
    description: '迎审数据归集、数据包管理、质量校验和字段映射。',
    icon: Database,
    layout: '数据需求 → 数据包管理 → 质量校验',
  },
  {
    path: '/standard-library',
    title: '检查标准库',
    pageId: 'stage_standard_library',
    category: 'data',
    categoryName: categoryNames.data,
    description: '检查要点、穿行测试模板、评分标准与规则输出联动。',
    icon: BookOpen,
    layout: '要点模型 → 来源权限 → 穿行模板 → 输出联动 → 变更留痕',
  },
  {
    path: '/review-workbench',
    title: '智能审查',
    pageId: 'stage_smart_review',
    category: 'review',
    categoryName: categoryNames.review,
    description: '规则命中、穿行验证和人工复核。',
    icon: Radar,
    layout: '审查任务列表 → 审查详情 → 线索复核',
  },
  {
    path: '/walkthrough-workbench',
    title: '穿行测试',
    pageId: 'stage_walkthrough_workbench',
    category: 'workpaper',
    categoryName: categoryNames.workpaper,
    description: '在检查任务内抽取业务样本，逐节点核验控制执行并沉淀审查记录。',
    icon: Footprints,
    layout: '测试实例 → 样本核验 → 审查记录',
  },
  {
    path: '/workpaper',
    title: '审查记录',
    pageId: 'stage_workpaper',
    category: 'workpaper',
    categoryName: categoryNames.workpaper,
    description: '审查过程记录的编制、取证、复核和归档管理。',
    icon: FileText,
    layout: '记录列表 → 记录详情 → 问题转化',
  },
  {
    path: '/evidence',
    title: '取证台账',
    pageId: 'stage_evidence_ledger',
    category: 'workpaper',
    categoryName: categoryNames.workpaper,
    description: '取证单记录、补证留痕、作废留痕与证据追溯。',
    icon: FileSearch,
    layout: '取证列表 → 取证详情 → 补证/作废',
  },
  {
    path: '/issues',
    title: '问题台账',
    pageId: 'stage_issues',
    category: 'workpaper',
    categoryName: categoryNames.workpaper,
    description: '问题草稿编写、确认定级和整改派发。',
    icon: AlertTriangle,
    layout: '问题列表 → 问题草稿 → 确认派发',
  },
  {
    path: '/rectify',
    title: '整改追踪',
    pageId: 'stage_rectify',
    category: 'rectify',
    categoryName: categoryNames.rectify,
    description: '整改派单、佐证提交、复核销号和整改报告编制。',
    icon: RefreshCw,
    layout: '整改列表 → 整改执行 → 报告编制',
  },
  {
    path: '/audit-center',
    title: '审核中心',
    pageId: 'stage_audit_center',
    category: 'rectify',
    categoryName: categoryNames.rectify,
    description: '集中处理计划校审、底稿复核、整改报告审核和报告发布审核。',
    icon: UserCheck,
    layout: '待处理 → 我发起的 → 已处理',
  },
  {
    path: '/report',
    title: '报告中心',
    pageId: 'stage_report_center',
    category: 'rectify',
    categoryName: categoryNames.rectify,
    description: '报告任务检索、智能撰写、审核发布和归档调阅。',
    icon: FileBarChart2,
    layout: '报告任务列表 → 报告详情 → 审核发布',
  },
  {
    path: '/knowledge-base',
    title: '知识库管理',
    pageId: 'stage_knowledge_base',
    category: 'data',
    categoryName: categoryNames.data,
    description: '法规库、案例库、模板方法库、智能检索问答和知识同步。',
    icon: Database,
    layout: '知识资产导航 → 管理工作区 → 同步去向',
  },
  {
    path: '/cockpit',
    title: '监督看板',
    pageId: 'stage_cockpit',
    category: 'plan',
    categoryName: categoryNames.plan,
    description: '全系统数据总览：待办统计、整改进度、风险态势一屏掌控。',
    icon: Activity,
    layout: '全链路态势大屏',
  },
]

export const defaultRoute = '/workplace'

export function getRouteMeta(pathname: string) {
  return icmRoutes.find((route) => route.path === pathname) || icmRoutes[0]
}

export const demoPath = icmRoutes.map((route) => route.path)
