import { useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { ArrowLeft, Archive, FileText, Search, Send } from 'lucide-react'

import { Button, Card, DataTable, DetailLine, Kpi, PageFrame, Tag, Toolbar, type Tone } from '../components/IcmPageKit'
import { useWorkflowStore, type ReportStatus } from '../store/workflowStore'

const tone = (status: ReportStatus): Tone => status === '审核通过' || status === '已归档' ? 'green' : status === '审核不通过' ? 'red' : status === '审核中' || status === '待审核' ? 'amber' : 'blue'

export default function ReportCenter() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const reports = useWorkflowStore((state) => state.reports)
  const rectifications = useWorkflowStore((state) => state.rectifications)
  const issues = useWorkflowStore((state) => state.issues)
  const createReport = useWorkflowStore((state) => state.createReport)
  const generateLedger = useWorkflowStore((state) => state.generateReportLedger)
  const submitAudit = useWorkflowStore((state) => state.submitReportAudit)
  const archiveReport = useWorkflowStore((state) => state.archiveReport)
  const [selectedId, setSelectedId] = useState(searchParams.get('report') ?? '')
  const [keyword, setKeyword] = useState('')
  const selected = reports.find((item) => item.id === selectedId)
  const available = rectifications.filter((item) => item.status === '已整改')
  const visible = useMemo(() => reports.filter((item) => !keyword.trim() || `${item.id}${item.title}${item.owner}${item.status}`.includes(keyword.trim())), [reports, keyword])
  const createFromRectification = (rectificationId: string) => setSelectedId(createReport(rectificationId))
  const linkedRectification = rectifications.find((item) => item.id === selected?.rectificationId)
  const linkedIssue = issues.find((item) => item.id === linkedRectification?.issueId)

  if (!selected) return <PageFrame title="报告中心" subtitle="仅从已整改且复核通过的事项创建报告，引用范围自动绑定问题、底稿、取证和整改记录。"><Toolbar><div className="icm-modal-search" style={{ maxWidth: 340 }}><Search size={15} /><input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="搜索报告编号、名称或编制单位" /></div><span className="icm-toolbar-spacer" /><Tag tone="blue">已整改可编制 {available.length} 项</Tag></Toolbar><div className="icm-grid cols-4" style={{ marginBottom: 12 }}><Kpi value={reports.length.toString()} label="报告任务" note="按整改事项创建" tone="blue" /><Kpi value={reports.filter((item) => item.status === '草稿').length.toString()} label="草稿" note="待生成报送台账" tone="amber" /><Kpi value={reports.filter((item) => item.status === '审核中' || item.status === '待审核').length.toString()} label="审核中" note="等待审核中心处理" tone="red" /><Kpi value={reports.filter((item) => item.status === '已归档').length.toString()} label="已归档" note="支持后续调阅" tone="green" /></div><div className="icm-report-list-layout"><Card title="报告任务" note="选择报告继续编制、审核或归档"><DataTable columns={['报告编号', '报告名称', '编制单位', '状态', '更新时间', '操作']} rows={visible.map((item) => [item.id, item.title, item.owner, <Tag tone={tone(item.status)}>{item.status}</Tag>, item.updatedAt, <button className="icm-link" type="button" onClick={(event) => { event.stopPropagation(); setSelectedId(item.id) }}>查看</button>])} onRowClick={(index) => setSelectedId(visible[index].id)} /></Card><aside><Card title="可编制报告" note="来源必须为已整改且复核通过"><div className="icm-list">{available.map((item) => <div className="icm-list-row" key={item.id}><div><div className="icm-list-title">{item.title}</div><div className="icm-list-meta">{item.id} · {item.owner} · 佐证 {item.proofCount} 份</div></div><Button type="primary-soft" onClick={() => createFromRectification(item.id)}>编制</Button></div>)}{!available.length ? <div className="icm-empty-inline">暂无满足报告编制条件的整改事项。</div> : null}</div></Card></aside></div></PageFrame>

  const references = selected.referenceIds.map((id) => ({ id, type: id.startsWith('ISS') ? '问题' : id.startsWith('WP') ? '底稿' : id.startsWith('EV') ? '取证' : '整改' }))
  return <PageFrame title={<span style={{ display: 'flex', alignItems: 'center', gap: 10 }}><Button type="default-soft" icon={<ArrowLeft size={15} />} onClick={() => setSelectedId('')}>返回列表</Button>报告详情</span>} subtitle={`${selected.id} · ${selected.title}`}><Toolbar><Tag tone={tone(selected.status)}>{selected.status}</Tag><span className="icm-toolbar-spacer" />{selected.status === '草稿' ? <Button type="primary" icon={<FileText size={14} />} onClick={() => generateLedger(selected.id)}>生成报送台账</Button> : selected.status === '待审核' ? <Button type="primary" icon={<Send size={14} />} onClick={() => submitAudit(selected.id)}>提交审核</Button> : selected.status === '审核通过' ? <Button type="primary" icon={<Archive size={14} />} onClick={() => archiveReport(selected.id)}>确认归档</Button> : selected.status === '审核不通过' ? <Button type="primary-soft" onClick={() => generateLedger(selected.id)}>修改后重新生成台账</Button> : selected.status === '已归档' ? <Tag tone="green">已归档</Tag> : <Tag tone="amber">审核中心处理中</Tag>}</Toolbar><div className="icm-report-detail-layout"><div><Card title="报告正文" note="报告引用项自动来源于已整改事项"><div className="icm-editor"><h2>{selected.title}</h2><p>编制单位：{selected.owner} · 数据截止日：{selected.updatedAt.slice(0, 10)} · 版本：V1.0</p><h3>一、整改概况</h3><p>{linkedRectification?.title}已完成整改，检查组复核结论为“{linkedRectification?.verifyConclusion}”。</p><h3>二、问题事实与依据</h3><p>{linkedIssue?.fact}</p><p>制度依据：{linkedIssue?.basis}</p><h3>三、整改措施与效果</h3><p>{linkedIssue?.suggestion}</p><h3>四、引用清单</h3><p>{references.map((item) => `${item.type} ${item.id}`).join('；')}</p></div></Card><Card title="引用数据" note="引用项版本随报告归档留痕"><DataTable columns={['类型', '编号', '状态']} rows={references.map((item) => [item.type, item.id, <Tag tone="green">已引用</Tag>])} /></Card></div><aside><Card title="报告状态"><DetailLine label="报送台账" value={selected.status === '草稿' ? '待生成' : `LED-${selected.id}`} /><DetailLine label="审核状态" value={<Tag tone={tone(selected.status)}>{selected.status}</Tag>} /><DetailLine label="关联整改" value={selected.rectificationId} /><DetailLine label="审核意见" value={selected.auditOpinion ?? '暂无'} /><DetailLine label="归档状态" value={selected.status === '已归档' ? '已归档' : '待归档'} /></Card><Card title="业务追溯"><div className="icm-trace-list"><button type="button" onClick={() => navigate(`/rectify?rect=${selected.rectificationId}`)}>{selected.rectificationId}<span>整改事项</span></button><button type="button" onClick={() => navigate(`/issues?issue=${linkedIssue?.id}`)}>{linkedIssue?.id ?? '-'}<span>问题台账</span></button><button type="button" onClick={() => navigate('/workpaper')}>{linkedIssue?.workpaperId ?? '-'}<span>审查记录</span></button></div></Card></aside></div></PageFrame>
}